import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import Header from "./components/Navbar/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="flex">
        <Sidebar />
        <main className="w-full">
          
          <Header />

          <div className="h-100 ">
            {children}
          </div>

         

        </main>
        



      </body>
    </html>
  );
}
